colNames = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
power = read.table('household_power_consumption.txt',header=TRUE,sep=';',skip=66636,nrows=2880,col.names = colNames)
png(filename = "plot1.png",width = 480, height = 480)
with(power,hist(Global_active_power,xlab = 'Global Active Power (kilowatts)',col = 'red',main = 'Global Active Power'))
dev.off()