colNames = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
power = read.table('household_power_consumption.txt',header=TRUE,sep=';',skip=66636,nrows=2880,col.names = colNames)
png(filename = "plot2.png",width = 480, height = 480)
with(power,plot(Global_active_power,main = 'Global Active Power',type='l',xaxt='n',ylab= 'Global Active Power (kilowatts)',xlab=''))
axis(1,at=c(1,1450,2900),labels=c('Thu','Fri','Sat'))
dev.off()